### ISSUE TITLE
panicking on code that uses `println`

### ISSUE THREAD

**Issue by mlvzk** [faiface/generics#1]
this code:
```go
package main

type Tuple(type T, type R) struct {
        a T
        b R
}

func main() {
        x := Tuple(int, string){5, "test"}
        println(x.b)
}
```

when run with `./generics -out out.go examples/tuple/tuple.go`
panics with stderr:
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x56b240]

goroutine 1 [running]:
github.com/faiface/generics/go/types.(*Checker).handleBailout(0xc000102000, 0xc00010dd98)
        /home/rwq/.go/src/github.com/faiface/generics/go/types/check.go:225 +0x98
panic(0x65eea0, 0x88bd50)
        /nix/store/jz7hkljvp8zdm95x4yxyddygs31mrsaf-go-1.11.6/share/go/src/runtime/panic.go:513 +0x1b9
github.com/faiface/generics/go/types.(*Checker).assignment(0xc000102000, 0x0, 0xc00000e900, 0x0, 0x0, 0xc00001a5e0, 0x13)
        /home/rwq/.go/src/github.com/faiface/generics/go/types/assignments.go:44 +0xb0
github.com/faiface/generics/go/types.(*Checker).builtin(0xc000102000, 0xc00000e900, 0xc00000e600, 0xc, 0xc000102000)
        /home/rwq/.go/src/github.com/faiface/generics/go/types/builtins.go:493 +0x3d69
github.com/faiface/generics/go/types.(*Checker).call(0xc000102000, 0xc00000e900, 0xc00000e600, 0x4e4a2c)
        /home/rwq/.go/src/github.com/faiface/generics/go/types/call.go:182 +0xb1c
github.com/faiface/generics/go/types.(*Checker).exprInternal(0xc000102000, 0xc00000e900, 0x6eb000, 0xc00000e600, 0x0, 0x0, 0x7f09659ed000)
        /home/rwq/.go/src/github.com/faiface/generics/go/types/expr.go:1450 +0x1d2f
github.com/faiface/generics/go/types.(*Checker).rawExpr(0xc000102000, 0xc00000e900, 0x6eb000, 0xc00000e600, 0x0, 0x0, 0x1)
        /home/rwq/.go/src/github.com/faiface/generics/go/types/expr.go:975 +0x81
github.com/faiface/generics/go/types.(*Checker).stmt(0xc000102000, 0x0, 0x6eb240, 0xc000076620)
        /home/rwq/.go/src/github.com/faiface/generics/go/types/stmt.go:331 +0x4011
github.com/faiface/generics/go/types.(*Checker).stmtList(0xc000102000, 0x0, 0xc00000a5c0, 0x2, 0x2)
        /home/rwq/.go/src/github.com/faiface/generics/go/types/stmt.go:123 +0xd6
github.com/faiface/generics/go/types.(*Checker).funcBody(0xc000102000, 0xc0000da310, 0xc00001451c, 0x4, 0xc000080720, 0xc00009eab0)
        /home/rwq/.go/src/github.com/faiface/generics/go/types/stmt.go:43 +0x167
github.com/faiface/generics/go/types.(*Checker).functionBodies(0xc000102000)
        /home/rwq/.go/src/github.com/faiface/generics/go/types/resolver.go:486 +0xeb
github.com/faiface/generics/go/types.(*Checker).checkFiles(0xc000102000, 0xc000071f08, 0x1, 0x1, 0x0, 0x0)
        /home/rwq/.go/src/github.com/faiface/generics/go/types/check.go:241 +0xc1
github.com/faiface/generics/go/types.(*Checker).Files(0xc000102000, 0xc000071f08, 0x1, 0x1, 0xc0000cf720, 0xc000071e01)
        /home/rwq/.go/src/github.com/faiface/generics/go/types/check.go:230 +0x49
github.com/faiface/generics/go/types.(*Config).Check(0xc00000e680, 0x0, 0x0, 0xc00000e440, 0xc000071f08, 0x1, 0x1, 0xc0000806c0, 0x0, 0x4cec01, ...)
        /home/rwq/.go/src/github.com/faiface/generics/go/types/api.go:359 +0x11a
main.main()
        /tmp/generics/main.go:62 +0x229
```

Valid Go code: https://play.golang.org/p/WT7YBjm4XH5

**Comment by faiface** [comment]
Try using `fmt.Println`. I will try and fix this later today.

**Comment by mlvzk** [comment]
I have a different problem when using imports:
`examples/tuple/tuple.go:3:8: could not import fmt (cannot import, possibly version skew (unknown export format version -1 ("i\x00\xe9\x03\xc6\x06\x18$GOROOT/src/fmt/print.go\x00\x05Write\x01b\x01n\x03err\x05Width\x03wid\x02ok\tPrecision\x04prec\x04Flag\x01c\x06Format\x01f\x05State\x06String\bGoString\x01w\x06Writer\x02io\x06format\x01a\aesc:0x1\aesc:0x9\x17$GOROOT/src/fmt/scan.go\bReadRune\x01r\x04size")) - reinstall package)`

**Comment by faiface** [comment]
What version of Go are you using?

**Comment by mlvzk** [comment]
`go version go1.11.6 linux/amd64`

**Comment by dbriemann** [comment]
I have the same problem with go1.12.5 on linux64.

**Comment by faiface** [comment]
Try replacing the whole `go/internal` directory in this repo with your local `$GOROOT/src/go/internal` directory. That could help.

I suspect the problem is that I made this from a copy of the `"go/*"` packages from Go 1.10 and importing in later versions is somehow incompatible internally.

**Comment by dbriemann** [comment]
This produces the following error:
```
✔ ~/Coding/go/src/github.com/faiface/generics [master|✚ 6…10] 
21:01 $ go install
go/importer/importer.go:10:2: code in directory /home/dlb/Coding/go/src/github.com/faiface/generics/go/internal/gccgoimporter expects import "go/internal/gccgoimporter"
go/importer/importer.go:11:2: code in directory /home/dlb/Coding/go/src/github.com/faiface/generics/go/internal/gcimporter expects import "go/internal/gcimporter"
go/importer/importer.go:12:2: code in directory /home/dlb/Coding/go/src/github.com/faiface/generics/go/internal/srcimporter expects import "go/internal/srcimporter"
```

**Comment by faiface** [comment]
Of course. Please, replace all occurrences of `go/internal` with `github.com/faiface/generics/go/internal`, so that the packages import from the repo instead of the stdlib.

**Comment by faiface** [comment]
I think I may have fixed the importing. (Didn't fix `println` yet, but you should be able to use `fmt.Println` now). Pull my changes and try if it works!

**Comment by mlvzk** [comment]
Imports work now, thanks
